export const PAGE_WIDTH = 794;
export const PAGE_HEIGHT = 1123;
export const MARGIN_TOP = 72;
export const MARGIN_BOTTOM = 72;
export const MARGIN_LEFT = 72;
export const MARGIN_RIGHT = 72;
export const CONTENT_HEIGHT = PAGE_HEIGHT - MARGIN_TOP - MARGIN_BOTTOM; // 931
export const PAGE_GAP = 40;
export const PARAGRAPH_SPACING = 10;
